### ISSUE TITLE
We need a safe word

### ISSUE THREAD

**Issue by babenzele** [kchungradio/schedule-api#2]
We need a safe word to exclude the event from being included in the results. 

Here are some shows that shouldn't be showing up:

- studio check up (no live broadcast)
- OPEN Self Managed Show (Talk to George)

Safe word in the title? Safe word in the description?

Currently only events whose title includes the words 'TENTATIVE' or 'TBD' will not be returned.

**Comment by lee2sman** [comment]
Maybe the word TEST or DONOTLIST ?
